# Generated by Django 6.0.3 on 2026-03-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='nombre',
            new_name='name',
        ),
    ]
