# Generated by Django 6.0.3 on 2026-03-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categoria_categories_rename_producto_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
